### ISSUE TITLE
evil-org-delete breaks evil-surround

### ISSUE THREAD

**Issue by kassick** [Somelauw/evil-org-improved#6]
When evil-org is enabled in a buffer, evil-surround's surround-delete stops working.

Without evil-org, the shortcut ds (delete surround) deletes the specified delimiters:
(| is cursor)
` -- {somet|hing}`
ds}
`something`

When evil-org is enabled, ds does not behaves as expected.

It apperrs that s enters evil-surround-edit with a parameter other then 'delete . It wants to *add* a surround and expects a movement to know which region to surround. 
```
one { t|wo } three

next paragraph
```

ds}     (understands } as paragraph movement )
}         (now it with {} up to the next paragraph

```
one { t{wo } three
} 
next paragraph
```

Screencast:
![output](https://user-images.githubusercontent.com/21071/33281744-768d8766-d38d-11e7-8c12-d66512650bb0.gif)

init.el : 
```
(package-initialize)

(require 'evil)
(require 'evil-org)
(require 'evil-surround)

(evil-mode 1)
(global-evil-surround-mode 1)
```

Package versions (installed from melpa):
- evil-org-20171107.1159
- evil-surround-20171127.910
- evil-20171126.659
- undo-tree-20170706.246
- goto-chg-20170917.1200

**Comment by Somelauw** [comment]
This project has been succeeded by https://github.com/Somelauw/evil-org-mode
I think the bug has already been resolved there.
